### ISSUE TITLE
Getting Error

### ISSUE THREAD

**Issue by pervaizdattoo** [datyayu/new-datyayu.xyz#6]
The site is not running. I'm getting this error.

```
 ERROR  Cannot convert undefined or null to object                                                            06:54:12

  at Function.assign (<anonymous>)
  at WebpackClientConfig.rules (node_modules\@nuxt\webpack\dist\webpack.js:4647:27)
  at WebpackClientConfig.config (node_modules\@nuxt\webpack\dist\webpack.js:4789:21)
  at WebpackClientConfig.config (node_modules\@nuxt\webpack\dist\webpack.js:4951:26)
  at WebpackBundler.getWebpackConfig (node_modules\@nuxt\webpack\dist\webpack.js:5240:19)
  at WebpackBundler.build (node_modules\@nuxt\webpack\dist\webpack.js:5247:12)
  at Builder.build (node_modules\@nuxt\builder\dist\builder.js:5602:30)

```

**Comment by datyayu** [comment]
Sorry for the late fix haha
Should be fixed after c0c6ea43b8c63d574f3171d7befa022e0a20437b
